version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u$$MYSQL_USER", "-p$$MYSQL_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  web:
    build: ./app
    container_name: flask_app
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    environment:
      DATABASE_URL: ${DATABASE_URL}
    networks:
      - app_network
    env_file:
      - ./.env
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
    command: python -m app.main # <-- 이 라인을 수정합니다.

networks:
  app_network:
    driver: bridge

volumes:
  db_data:
